# Generated by Django 4.0.4 on 2022-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='Введите число месяца')),
                ('month', models.PositiveIntegerField(help_text='Введите номер месяца')),
                ('year', models.PositiveIntegerField(help_text='Введите год из диапазона 2019-2022')),
            ],
        ),
    ]
